-- MySQL Script generated by MySQL Workbench
-- Wed Aug  5 19:21:07 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbAcceso
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbAcceso` ;

-- -----------------------------------------------------
-- Schema dbAcceso
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbAcceso` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `dbAcceso` ;

-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario` (
  `idusuario` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `aPaterno` VARCHAR(45) NOT NULL,
  `aMaterno` VARCHAR(45) NOT NULL,
  `fotoUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login` (
  `email` VARCHAR(25) NOT NULL,
  `clave` VARCHAR(12) NOT NULL,
  `tipoUsuario` ENUM('Administrador', 'Visitante') NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`email`, `usuario_idusuario`),
  INDEX `fk_login_usuario_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_login_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `privilegio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `privilegio` (
  `tipoUsuario` ENUM('Administrador', 'Visitante') NOT NULL,
  `formulario` VARCHAR(45) NULL,
  PRIMARY KEY (`tipoUsuario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
